#### find all
GET http://localhost:8080/api/producto/all



#### find by id
GET http://localhost:8080/api/producto/1



##### insertar nuevo produco
POST http://localhost:8080/api/producto
Content-Type: application/json

{
     "descripcion":"xxssx",
     "precio":10.50
}



##### actualizar produco
PUT http://localhost:8080/api/producto/1
Content-Type: application/json

{
     "descripcion":"Agua",
     "precio":10.50
}




##### actualizar produco
DELETE  http://localhost:8080/api/producto/1
Content-Type: application/json

